config/routes.rb
Weightable::Application.routes.draw do

  get "static_pages/landing"
  devise_for :users

  root 'static_pages#landing'

  resources :friendships

  resources :users do
    resources :weigh_ins do
      resources :comments
    end
  end
end




#                     Prefix Verb   URI Pattern                                                        Controller#Action
#           new_user_session GET    /users/sign_in(.:format)                                           devise/sessions#new
#               user_session POST   /users/sign_in(.:format)                                           devise/sessions#create
#       destroy_user_session DELETE /users/sign_out(.:format)                                          devise/sessions#destroy
#              user_password POST   /users/password(.:format)                                          devise/passwords#create
#          new_user_password GET    /users/password/new(.:format)                                      devise/passwords#new
#         edit_user_password GET    /users/password/edit(.:format)                                     devise/passwords#edit
#                            PATCH  /users/password(.:format)                                          devise/passwords#update
#                            PUT    /users/password(.:format)                                          devise/passwords#update
#   cancel_user_registration GET    /users/cancel(.:format)                                            devise/registrations#cancel
#          user_registration POST   /users(.:format)                                                   devise/registrations#create
#      new_user_registration GET    /users/sign_up(.:format)                                           devise/registrations#new
#     edit_user_registration GET    /users/edit(.:format)                                              devise/registrations#edit
#                            PATCH  /users(.:format)                                                   devise/registrations#update
#                            PUT    /users(.:format)                                                   devise/registrations#update
#                            DELETE /users(.:format)                                                   devise/registrations#destroy
#                       root GET    /                                                                  users#index
#                friendships GET    /friendships(.:format)                                             friendships#index
#                            POST   /friendships(.:format)                                             friendships#create
#             new_friendship GET    /friendships/new(.:format)                                         friendships#new
#            edit_friendship GET    /friendships/:id/edit(.:format)                                    friendships#edit
#                 friendship GET    /friendships/:id(.:format)                                         friendships#show
#                            PATCH  /friendships/:id(.:format)                                         friendships#update
#                            PUT    /friendships/:id(.:format)                                         friendships#update
#                            DELETE /friendships/:id(.:format)                                         friendships#destroy
#     user_weigh_in_comments GET    /users/:user_id/weigh_ins/:weigh_in_id/comments(.:format)          comments#index
#                            POST   /users/:user_id/weigh_ins/:weigh_in_id/comments(.:format)          comments#create
#  new_user_weigh_in_comment GET    /users/:user_id/weigh_ins/:weigh_in_id/comments/new(.:format)      comments#new
# edit_user_weigh_in_comment GET    /users/:user_id/weigh_ins/:weigh_in_id/comments/:id/edit(.:format) comments#edit
#      user_weigh_in_comment GET    /users/:user_id/weigh_ins/:weigh_in_id/comments/:id(.:format)      comments#show
#                            PATCH  /users/:user_id/weigh_ins/:weigh_in_id/comments/:id(.:format)      comments#update
#                            PUT    /users/:user_id/weigh_ins/:weigh_in_id/comments/:id(.:format)      comments#update
#                            DELETE /users/:user_id/weigh_ins/:weigh_in_id/comments/:id(.:format)      comments#destroy
#             user_weigh_ins GET    /users/:user_id/weigh_ins(.:format)                                weigh_ins#index
#                            POST   /users/:user_id/weigh_ins(.:format)                                weigh_ins#create
#          new_user_weigh_in GET    /users/:user_id/weigh_ins/new(.:format)                            weigh_ins#new
#         edit_user_weigh_in GET    /users/:user_id/weigh_ins/:id/edit(.:format)                       weigh_ins#edit
#              user_weigh_in GET    /users/:user_id/weigh_ins/:id(.:format)                            weigh_ins#show
#                            PATCH  /users/:user_id/weigh_ins/:id(.:format)                            weigh_ins#update
#                            PUT    /users/:user_id/weigh_ins/:id(.:format)                            weigh_ins#update
#                            DELETE /users/:user_id/weigh_ins/:id(.:format)                            weigh_ins#destroy
#                      users GET    /users(.:format)                                                   users#index
#                            POST   /users(.:format)                                                   users#create
#                   new_user GET    /users/new(.:format)                                               users#new
#                  edit_user GET    /users/:id/edit(.:format)                                          users#edit
#                       user GET    /users/:id(.:format)                                               users#show
#                            PATCH  /users/:id(.:format)                                               users#update
#                            PUT    /users/:id(.:format)                                               users#update
#                            DELETE /users/:id(.:format)                                               users#destroy

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :profilepic, ImageUploader

  has_many :weigh_ins
  has_many :comments, through: :weigh_ins
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @weigh_ins = @user.weigh_ins
    @weigh_in = WeighIn.new user_id: @user.id
    @comment = Comment.new
  end

  def index
    @users = User.search(params[:search])
    # @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profilepic, :startweight, :desiredweight, :bio)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/index.html.haml
- if current_user != nil
  %h1
    Welcome, 
    = current_user.name
    !

%h5.search Search for Users
= form_tag users_path, :method => 'get' do
  = text_field_tag :search, params[:search]
  = submit_tag "Search", :name => nil

%br
%br
%br
    

%table
  %thead.users
    %th.users 
    %th.users Name
    %th.users About
    - if current_user != nil
      %th.users Friends?
  %tbody
  - @users.each do |user|
    %tr
      %td= user.profilepic
      %td= link_to user.name, user
      %td= user.bio
      - if current_user != nil
        - if current_user.friendships.find_by_friend_id(user.id)
          %td Already Friends!
        - elsif user.id != current_user.id
          %td= link_to "Add As Friend!", friendships_path(:friend_id => user), :method => :post

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

app/views/users/show.html.haml
%div.user  
  %h1= @user.name
  - if @user != current_user
    - if current_user.friends.find_by(name: @user.name)
      You are already friends!
    - else
      = link_to "Add As Friend!", friendships_path(:friend_id => @user), :method => :post
  %br
  %br

  %p= @user.bio

%div.friends
  %h3 Friends
  - if @user.friendships.length != 0
    %table
      %tbody
        - @user.friendships.each do |friendship|
          %tr
            %td= friendship.friend.profilepic
            %td= friendship.friend.name
            - if @user == current_user
              %td= link_to "remove", friendship, :method => :delete
  - else
    %p You have Friended no one.&nbsp&nbsp&nbsp:(


  %h3 Friended by
  - if @user.inverse_friendships.length != 0
    %table
      %tbody        
        - @user.inverse_friends.each do |inverse_friend|
          %tr
            %td= inverse_friend.name
  - else
    %p No one has Friended you.&nbsp&nbsp&nbsp:(
%div.weighin
  - if @user == current_user
    %h3 Add a Weigh-In
    = form_for [@user, @weigh_in] do |f|
      = f.text_field :currentweight, :placeholder => 'How Much Do You Weigh Today?'
      = f.text_field :description, :placeholder => 'How did you lose it?'
      = f.label 'Upload a picture at your current weight'
      = f.file_field :weightpic

      = f.submit 'Create Weigh-In', :class => "button"

  %h4 Weigh-Ins
  %ul 
    - if @user.weigh_ins.length == 0
      %p No Weigh-Ins Yet!
    -else
      - @user.weigh_ins.reverse_each do |weigh_in|
        - next if weigh_in.new_record?
        %h5 
          = "Weigh-in ##{weigh_in.id}: #{weigh_in.created_at.strftime("%m/%d/%y at %l:%M%P")}"
        - if weigh_in.weightpic.blank?
          <no image>
        - else
          %img{src: weigh_in.weightpic.url(:medium)}
        %li
          = "Today I weigh: #{weigh_in.currentweight} lbs."
        %li
          = "What I did to get to this weight: #{weigh_in.description}"
        %li
          =render partial: 'comments/comment', locals: {weigh_in: weigh_in, user: @user, comment: @comment, comments: @comments}
        - if @user == current_user
          %li
            %span
            = link_to 'Edit', '#' 
            \|
            %span
            = link_to ' Delete', '#', method: :delete, data: { confirm: 'Are you sure?' }
        %br
        %br

%br
%br

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml